//
//  AWSConfiguration.swift
//  My Mind
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from Amazon Mobile Hub
//
//

import AWSCore


// Cognito User Pools Identity Id
let AWSCognitoUserPoolId: String = "eu-west-2_GyTxJ1kUG"

// Cognito User Pools App Client Id
let AWSCognitoUserPoolAppClientId: String = "2qlv4rkq1ea4sg0v6loen29lph"

// Cognito User Pools Region
let AWSCognitoUserPoolRegion: AWSRegionType = .EUWest2

// Cognito User Pools Client Secret
let AWSCognitoUserPoolClientSecret: String = "19uu3s8skbcoqcdn4dhj6q180q31laf8cr4bopd4k36t8k01jn3j"
